server:
  port: 8212
spring:
  main:
    web-application-type: reactive
gateway:
  routes:
    config:
      data-id: gateway-routes  #动态路由
      group: shop
      namespace: b9c41727-0eb3-4fe3-8ecc-4c1cdb773486



